Add tag check and release admin

diff --git a/.github/workflows/_build-wheel-release-upload.yml b/.github/workflows/_build-wheel-release-upload.yml
--- a/.github/workflows/_build-wheel-release-upload.yml
+++ b/.github/workflows/_build-wheel-release-upload.yml
@@ -17,7 +17,36 @@ on:
         required: true
 
 jobs:
+  tag-check:
+    runs-on: ubuntu-latest
+    outputs:
+      tag_valid: ${{ steps.tag-check.outputs.tag_valid }}
+    steps:
+      - name: Extract and validate tag for (pre)-release
+        id: tag-check
+        run: |
+          TAG_NAME=${GITHUB_REF#refs/tags/}
+
+          # Check if the tag matches the pattern, e.g. 3.1.32 or 0.1.3rc0
+          if [[ "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || [[ "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+rc[0-9]+$ ]]; then
+            echo "tag_valid=true" >> $GITHUB_OUTPUT
+          fi
+
+  release-privilege-check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check user role
+        # FIXME: Replace sbillinge to bobleesj
+        run: |
+          if [ "${{ github.actor }}" != "bobleesj" ]; then
+            echo "Error: Unauthorized user"
+            exit 1
+          fi
+          echo "User sbillinge is allowed to run this workflow."
+        
   build-package:
+    needs: [tag-check, release-privilege-check]
+    if: needs.tag-check.outputs.tag_valid == 'true'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
