Use conditional statement for all jobs

diff --git a/.github/workflows/_build-wheel-release-upload.yml b/.github/workflows/_build-wheel-release-upload.yml
--- a/.github/workflows/_build-wheel-release-upload.yml
+++ b/.github/workflows/_build-wheel-release-upload.yml
@@ -37,6 +37,8 @@ jobs:
 
   update-changelog:
     needs: [build-pure-python-package, build-non-pure-python-package]
+    # The always() function is necessary to ensure that we wait for both build jobs to complete, even if one of them is skipped.
+    # Without always(), if one of the needed jobs is skipped, the `update-changelog` job will not be executed.
     if: "always() && !contains(github.ref, 'rc')"
     runs-on: ubuntu-latest
     steps:
@@ -68,9 +70,18 @@ jobs:
   # Check for rc as an ouput, use it as a variable
   github-pre-release:
     needs: [build-pure-python-package, build-non-pure-python-package]
-    if: contains(github.ref, 'rc')
+    if: "always() && contains(github.ref, 'rc')"
     runs-on: ubuntu-latest
     steps:
+      - name: Fail github-pre-release job if building job failed
+        run: |
+          if [ "${{ needs.build-pure-python-package.result }}" == 'success' ] || [ "${{ needs.build-non-pure-python-package }}" == 'success' ]; then
+            echo "Ready to pre-release on GitHub..."
+          else
+            echo "Previous build-package job failed; exiting..."
+            exit 1
+          fi
+
       - name: Generate GH release notes for pre-release
         uses: softprops/action-gh-release@v2
         with:
@@ -80,10 +91,18 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
 
   github-release:
-    needs: [build-pure-python-package, build-non-pure-python-package, update-changelog]
-    if: "!contains(github.ref, 'rc')"
+    needs: [update-changelog]
+    if: "always() && !contains(github.ref, 'rc')"
     runs-on: ubuntu-latest
     steps:
+      - name: Fail github-release job if CHANGELOG udpate failed
+        run: |
+          if [ "${{ needs.update-changelog.result }}" == 'success' ]; then
+            echo "Ready to release on GitHub..."
+          else
+            echo "Previous update-changelog job failed; exiting..."
+            exit 1
+          fi
       - name: Checkout the repository
         uses: actions/checkout@v4
         with:
