Do not release

diff --git a/.github/workflows/_build-wheel-release-upload.yml b/.github/workflows/_build-wheel-release-upload.yml
--- a/.github/workflows/_build-wheel-release-upload.yml
+++ b/.github/workflows/_build-wheel-release-upload.yml
@@ -69,88 +69,87 @@ jobs:
           commit_message: update changelog
           branch: main
 
-  github-pre-release:
-    needs: [build-pure-python-package, build-non-pure-python-package]
-    if: "always() && contains(github.ref, 'rc')"
-    runs-on: ubuntu-latest
-    steps:
-      - name: Fail github-pre-release job if building job failed
-        run: |
-          if [ "${{ needs.build-pure-python-package.result }}" == 'success' ] || [ "${{ needs.build-non-pure-python-package.result }}" == 'success' ]; then
-            echo "Ready to pre-release on GitHub..."
-          else
-            echo "Previous build-package job failed; exiting..."
-            exit 1
-          fi
+  # github-pre-release:
+  #   needs: [build-pure-python-package, build-non-pure-python-package]
+  #   if: "always() && contains(github.ref, 'rc')"
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Fail github-pre-release job if building job failed
+  #       run: |
+  #         if [ "${{ needs.build-pure-python-package.result }}" == 'success' ] || [ "${{ needs.build-non-pure-python-package.result }}" == 'success' ]; then
+  #           echo "Ready to pre-release on GitHub..."
+  #         else
+  #           echo "Previous build-package job failed; exiting..."
+  #           exit 1
+  #         fi
 
-      - name: Generate GH release notes for pre-release
-        uses: softprops/action-gh-release@v2
-        with:
-          prerelease: true
-          generate_release_notes: true
-          token: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Generate GH release notes for pre-release
+  #       uses: softprops/action-gh-release@v2
+  #       with:
+  #         prerelease: true
+  #         generate_release_notes: true
+  #         token: ${{ secrets.GITHUB_TOKEN }}
 
-  github-release:
-    needs: [update-changelog]
-    if: "always() && !contains(github.ref, 'rc')"
-    runs-on: ubuntu-latest
-    steps:
-      - name: Fail github-release job if CHANGELOG update failed
-        run: |
-          if [ "${{ needs.update-changelog.result }}" == 'success' ]; then
-            echo "Ready to release on GitHub..."
-          else
-            echo "Previous update-changelog job failed; exiting..."
-            exit 1
-          fi
-      - name: Checkout the repository
-        uses: actions/checkout@v4
-        with:
-          ref: main
-      - name: Generate GH release notes for release
-        run: |
-          wget https://raw.githubusercontent.com/Billingegroup/release-scripts/v0/.github/workflows/get-latest-changelog.py
-          python get-latest-changelog.py "${{ github.ref_name }}"
-      - name: Release
-        uses: softprops/action-gh-release@v2
-        with:
-          body_path: CHANGELOG.txt
-          token: ${{ secrets.GITHUB_TOKEN }}
-          draft: true
+  # github-release:
+  #   needs: [update-changelog]
+  #   if: "always() && !contains(github.ref, 'rc')"
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Fail github-release job if CHANGELOG update failed
+  #       run: |
+  #         if [ "${{ needs.update-changelog.result }}" == 'success' ]; then
+  #           echo "Ready to release on GitHub..."
+  #         else
+  #           echo "Previous update-changelog job failed; exiting..."
+  #           exit 1
+  #         fi
+  #     - name: Checkout the repository
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: main
+  #     - name: Generate GH release notes for release
+  #       run: |
+  #         wget https://raw.githubusercontent.com/Billingegroup/release-scripts/v0/.github/workflows/get-latest-changelog.py
+  #         python get-latest-changelog.py "${{ github.ref_name }}"
+  #     - name: Release
+  #       uses: softprops/action-gh-release@v2
+  #       with:
+  #         body_path: CHANGELOG.txt
+  #         token: ${{ secrets.GITHUB_TOKEN }}
 
-  pypi-publish:
-    needs: [github-pre-release, github-release]
-    runs-on: ubuntu-latest
-    if: always()  # This job will always initiate regardless of the success or failure of the needed jobs
-    steps:
-      - name: Fail pypi-publish job if github-(pre)-release job failed
-        run: |
-          if [ "${{ needs.github-pre-release.result }}" == 'success' ] || [ "${{ needs.github-release.result }}" == 'success' ]; then
-            echo "Ready for PyPI release..."
-          else
-            echo "Previous github-(pre)-release job failed; exiting..."
-            exit 1
-          fi
+  # pypi-publish:
+  #   needs: [github-pre-release, github-release]
+  #   runs-on: ubuntu-latest
+  #   if: always()  # This job will always initiate regardless of the success or failure of the needed jobs
+  #   steps:
+  #     - name: Fail pypi-publish job if github-(pre)-release job failed
+  #       run: |
+  #         if [ "${{ needs.github-pre-release.result }}" == 'success' ] || [ "${{ needs.github-release.result }}" == 'success' ]; then
+  #           echo "Ready for PyPI release..."
+  #         else
+  #           echo "Previous github-(pre)-release job failed; exiting..."
+  #           exit 1
+  #         fi
 
-      - uses: actions/download-artifact@v4
-        with:
-          pattern: '**/*' # Make sure all files are downloaded, including wheels
-          path: dist
-          merge-multiple: true
+  #     - uses: actions/download-artifact@v4
+  #       with:
+  #         pattern: '**/*' # Make sure all files are downloaded, including wheels
+  #         path: dist
+  #         merge-multiple: true
 
-      - name: Setup Python for PyPI upload
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.13'
+  #     - name: Setup Python for PyPI upload
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: '3.13'
 
-      - name: Install Twine
-        run: |
-          python -m pip install --upgrade pip
-          pip install twine
+  #     - name: Install Twine
+  #       run: |
+  #         python -m pip install --upgrade pip
+  #         pip install twine
 
-      - name: Publish package to PyPI
-        env:
-          TWINE_USERNAME: __token__
-          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
-        run: |
-          twine upload dist/* --verbose
+  #     - name: Publish package to PyPI
+  #       env:
+  #         TWINE_USERNAME: __token__
+  #         TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
+  #       run: |
+  #         twine upload dist/* --verbose
